document.getElementById("logo").style.cursor = "pointer";
document.getElementById('logo').addEventListener('click', (event) => { window.location.href = "home.html" });
document.getElementById("home").style.cursor = "pointer";
document.getElementById('home').addEventListener('click', (event) => { window.location.href = "home.html" });
document.getElementById("events").style.cursor = "pointer";
document.getElementById('events').addEventListener('click', (event) => { window.location.href = "events.html" });
document.getElementById("teams").style.cursor = "pointer";
document.getElementById('teams').addEventListener('click', (event) => { window.location.href = "teams.html" });
document.getElementById("leaderboards").style.cursor = "pointer";
document.getElementById('leaderboards').addEventListener('click', (event) => { window.location.href = "leaderboard.html" });
document.getElementById("stats").style.cursor = "pointer";
document.getElementById('stats').addEventListener('click', (event) => { window.location.href = "stats.html" });